version: '3.8'

services:
  kw-build:
    image: kw-build-container
    build:
      context: .
      dockerfile: .docker/Dockerfile
    volumes:
      - ./:/build/komodo-wallet-desktop
    working_dir: /build/komodo-wallet-desktop/ci_tools_atomic_dex
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - TZ=Etc/UTC
      - SHELL=/bin/bash
      - QT_INSTALL_CMAKE_PATH=/root/Qt/5.15.2/gcc_64/lib/cmake
      - QT_ROOT=/root/Qt/5.15.2
      - PATH=/root/Qt/5.15.2/gcc_64/bin:/root/.nimble/bin:$PATH
      - CXX=clang++-12
      - CC=clang-12
    command: bash -c "./ci_tools_atomic_dex build Debug && ./ci_tools_atomic_dex bundle Debug"
    tty: true
    stdin_open: true
