if (NOT APPLE)
    find_program(ANTARA_CXX_COMPILER clang++)
    find_program(ANTARA_C_COMPILER clang)
    set(CMAKE_CXX_COMPILER "${ANTARA_CXX_COMPILER}" CACHE STRING "")
    set(CMAKE_C_COMPILER "${ANTARA_C_COMPILER}" CACHE STRING "")
endif ()

if (WIN32)
    add_definitions(-D_CRT_SECURE_NO_WARNINGS)
endif ()