if (CMAKE_BUILD_TYPE STREQUAL "Release")
    if (APPLE)
        include(CheckIPOSupported)
        check_ipo_supported(RESULT ipo_supported OUTPUT output)
        if (ipo_supported)
            #set(CMAKE_INTERPROCEDURAL_OPTIMIZATION ON)
            message(STATUS "We are in release - Successfully enabled IPO")
        else ()
            message(WARNING "IPO NOT SUPPORTED - Skipping reason: ${output}")
        endif ()
    endif ()
endif ()